spring:
  datasource:
    url: jdbc:mysql://database-1.chz2rw6hxdnq.ap-northeast-2.rds.amazonaws.com:3306/employees?useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1
      auto-commit: false
    password: rladudtjr1!
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
        generate_statistics: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org.springframework.orm.jpa: TRACE
    org.springframework.transaction: TRACE
    java.sql: DEBUG
    org.hibernate.stat.category: DEBUG
